### PR TITLE
Eperez static urls

### PR DESCRIPTION
**Pull request by enriquepablo**
Needed to have local static assets for development

### CODE REVIEW

**Comment by fredrikt** [comment]
I'm not sure I understand what 'local static assets' are here? Do you not want to serve the js/css/etc using the eduid-html docker container on http://html.docker/static/?

**Comment by enriquepablo** [comment]
Yes definitely. But when the setting "static_url" is not configured, we have a static_view configured at e.g. [the dashboard](https://github.com/SUNET/eduid-dashboard/blob/master/eduiddashboard/__init__.py#L491) that needs pyramid to heed the SERVER_NAME header (if we serve the dashboard under some path), and the removed configuration interferes with that.

Any other case(e.g. the dashboard is served at the root in its own domain) will work just the same.

**Comment by enriquepablo** [comment]
The pasteDeploy#prefix filter is a different way to define the SERVER_NAME env var that was not really working, see:

http://pythonpaste.org/deploy/class-paste.deploy.config.PrefixMiddleware.html

**Comment by fredrikt** [comment]
I think since we removed all css/js from eduid-{signup,dashboard}, static_url is a required configuration parameter now?
I understand it is not enforced at the moment, but am saying maybe the solution is to put it on the list of required configuration parameters. I added it in eduid-developer (for dashboard) this morning BTW.

**Comment by enriquepablo** [comment]
I am ok with setting static_url as required. In that case we need to get rid of all those `if settings.get('static_url', False)` (e.g. [in the dashboard](https://github.com/SUNET/eduid-dashboard/blob/master/eduiddashboard/__init__.py#L488).

But even so I think we do not want to have the PasteDeploy#prefix filters in place. They should be used like this:

filter-with = proxy-prefix

[filter:proxy-prefix]
use = egg:PasteDeploy#prefix
prefix = /signup

And if the `prefix = /signup` is omitted, it will be assumed to be `/` and the SERVER_NAME fron the reverse proxy will be ignored.

My first comment in this thread was wrong in focusing on static urls; any other url (such as urls for redirects) will be affected by this (if I'm not wrong). I'll check.

**Comment by fredrikt** [comment]
Sorry for being dense, are you saying we won't need filter:proxy-prefix at all?

I'm sure you are right for the current master branch, but are you saying it is not needed with the planned upcoming changes in the service_discovery branch either?

**Comment by enriquepablo** [comment]
I've checked:

In my present setup I have a nginx in the docker host (my laptop) that serves as reverse proxy for all apps. This is so I can easily serve them over the local network to the front-end guy. So I have the dashboard under /dashboard/, having nginx pass the X-Forwarded- and SERVER_NAME headers to the proxied app.
If I add the PasteDeploy#prefix filter to the dashboard ini file, and (being logged out) I go to http://10.35.1.123/dashboard/ (10.35.1.123 being my local IP), I am redirected to http://10.35.1.123/saml2/login/?next=/, and that is wrong, it should be http://10.35.1.123/dashboard/saml2/login/?next=/ ; on / is the IdP, and it knows nothing about /saml2/login/?next=/ .

**Comment by enriquepablo** [comment]
(Sorry did not notice your last comment before my last, reading it)

**Comment by enriquepablo** [comment]
Ok it's me who is being dense, vulcand cannot set SERVER_NAME. Sorry for the insistence :-/

**Comment by enriquepablo** [comment]
outdated

**Pull request closed without merging**
